version: "3.9"
volumes:
  php-fpm-socket-hoge:

services:
  web:
    build: ./nginx
    ports:
      - 8080:80
    volumes:
      - php-fpm-socket-hoge:/var/run/php-fpm
      - ./backend:/work/backend